# Site settings
remote_theme : "mmistakes/minimal-mistakes"
minimal_mistakes_skin : "air"
title : Kanishke Gamagedara
title_separator : "-"
subtitle : # site tagline that appears below site title in masthead
name : "Kanishke Gamagedara"
description : "My personal website"
url : https://kanishkegb.github.io/ # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl : / # the subpath of your site, e.g. "/blog"
repository : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs : false # true, false (default)
words_per_minute : 200
paginate: 5
paginate_path: "/page:num/"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


# Site Author
author:
  name             : 
  avatar           : "/assets/images/bio-photo.jpg"
  bio              :
  location         : "Washington, DC"
  email            : "kanishkegb@gmail.com"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "kanishkegb"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        : "kanishkegb"
  lastfm           :
  linkedin         : "kanishkegb"
  pinterest        :
  soundcloud       :
  stackoverflow    : 8371691/kani # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"


# Build settings
# Reading Files
include:
  - .htaccess
  - _pages
  - _includes
  - _layouts
exclude: README.md"]
exclude: [vendor]

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: false
      show_date: false
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      show_date: true

atom_feed:
  hide: true


footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kanishkegb"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kanishkegb"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/kanishkegb"


# fixes "No GitHub API authentication" error
github: [metadata]