# Site settings
theme: minimal-mistakes-jekyll
title: Kanishke Gamagedara

minimal_mistakes_skin: "air"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Site Author
author:
  name             : "Kanishke Gamagedara"
  avatar           : "/images/bio-photo.jpg"
  bio              : "Add a bio"
  location         : "Washington, DC"
  email            : "kanishkegb@gmail.com"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "kanishkegb"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        : "kanishkegb"
  lastfm           :
  linkedin         : "kanishkegb"
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"


# Build settings
exclude: ["README.md"]

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: foo
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
